services:
  - type: web
    name: quickcart-api
    env: python
    region: oregon
    plan: free
    buildCommand: cd server && pip install -r ../requirements.txt
    startCommand: cd server && python run.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://your-app.vercel.app
    healthCheckPath: /api/health
